name: "Github Action Contributor"
description: "Target README.md"
inputs:
  listType: # id of input
    description: "To output contributors in list type of usernames"
    required: false
    default: "false"
  imageSize: # id of input
    description: "Size of square images in the stack"
    required: false
    default: "100"
  columnsPerRow: # id of input
    description: "Number of columns in a row"
    required: false
    default: "6"
  header: # id of input
    description: "Header of the section"
    required: false
    default: "Thank You All For Great Help"
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: 'heart'  
  color: 'red'

